[project]
name = "evotool-ol"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ag2>=0.8.3",
    "bilibili-api-python>=17.1.4",
    "mcp[cli]>=1.5.0",
]
